import Image from "next/image"

export const metadata = {
  title: 'SMyT',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Image 
            width={170}
            height={95}
            alt="data"
           src='/logo1.png' 
            />
            <Image 
            width={300}
            height={90}
            alt="data"
           src='/logo2.png'

            />
        {children}
        </body>
    </html>
  )
}
